// apps/qw-oracle/scripts/generate-pg-migration.ts
//
// One-shot generator: reads scripts/load-knowledge/schema.ts (the SQLite
// source-of-truth) and emits Postgres-dialect migration SQL covering the
// 30-table Layer 1 schema. Throwaway after Arc 1 ships -- post-Arc-1 schema
// evolution lives in append-only .sql migrations under db/migrations/, not
// re-runs of this script.
//
// Why a generator at all: the legacy monolithic plan hand-typed CREATE TABLE
// blocks from memory and shipped wrong CHECK enum values, missing UNIQUE
// constraints, and incomplete column lists. Decisions D3 + F4 mandate that
// the structural port be mechanical from schema.ts so the only failure mode
// is "the generator's dialect transforms are wrong" -- catchable by Task 5's
// per-table column-list diff.
//
// The migration blocks (ENTITIES_V*_MIGRATION_SQL,
// PROTOCOL_MESSAGE_KIND_V16_MIGRATION_SQL, ASSET_LOADER_SITES_V8_MIGRATION_SQL,
// PROJECT_CHECK_V10_MIGRATION_SQL, SOURCE_STATE_TRANSITIONS_V9_MIGRATION_SQL,
// SCHEMA_V7_MIGRATION_SQL, SCHEMA_V11_MIGRATION_SQL) are SQLite-only rebuild
// SQL for migrating an existing DB through CHECK widenings. The fresh-DB
// "additions" blocks (SCHEMA_V*_ADDITIONS_SQL) already carry the final
// widened shape (per the comment in schema.ts:51-56), so the generator
// concatenates only the additions blocks and the V1 base block.

import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SCHEMA_TS_PATH = resolve(__dirname, 'load-knowledge/schema.ts');

// Source order matches the applySchema() exec order in schema.ts:1587-1686:
// V1 first (versions, entities, the four "always there" per-version tables,
// change_events, source_state_transitions), then V2-V15 additions in order.
// V7-V11 are migration-only (see header comment); V8-V11's structural changes
// are already baked into the V1 / V3 / V5 blocks they touched.
const BLOCK_NAMES = [
  'SCHEMA_V1_SQL',
  'SCHEMA_V2_ADDITIONS_SQL',
  'SCHEMA_V3_ADDITIONS_SQL',
  'SCHEMA_V4_ADDITIONS_SQL',
  'SCHEMA_V5_ADDITIONS_SQL',
  'SCHEMA_V6_ADDITIONS_SQL',
  'SCHEMA_V12_ADDITIONS_SQL',
  'SCHEMA_V13_ADDITIONS_SQL',
  'SCHEMA_V14_ADDITIONS_SQL',
  'SCHEMA_V15_ADDITIONS_SQL',
] as const;

// Boolean-shaped column allowlist. SQLite stored these as INTEGER (0/1);
// Postgres wants BOOLEAN. The loader port (Tasks 7-9) will pass JS true/false
// instead of 0/1. The legacy SQLite values 0/1 are accepted by Postgres
// JS-driver coercion only when the JS value is a literal boolean, so the
// adapter ports must convert.
const BOOLEAN_COLUMN_NAMES = new Set([
  'server_only',           // cvar_versions
  'teamplay_restricted',   // macro_versions
  'dev_only',              // asset_loader_sites
  'source_verified',       // asset_path_rules
  // ruleset_versions.restrict_*: nullable INTEGER -> nullable BOOLEAN.
  'restrict_triggers',
  'restrict_packet',
  'restrict_particles',
  'restrict_play',
  'restrict_logging',
  'restrict_rollangle',
  'restrict_ipc',
  'restrict_exec',
  'restrict_setcalc',
  'restrict_seteval',
  'restrict_setex',
]);

// Timestamp coercion allowlist. SQLite stored ISO 8601 strings as TEXT.
// Postgres TIMESTAMPTZ accepts ISO strings on insert, so the loader's
// existing `new Date().toISOString()` calls pass through unchanged.
const TIMESTAMP_COLUMN_NAMES = new Set([
  'extracted_at',
  'created_at',
  'updated_at',
  'tag_date',
]);

function extractBlock(source: string, name: string): string {
  // Match: const NAME = `<contents>`;
  // Non-greedy capture between the backticks.
  const re = new RegExp(`const ${name} = \`([\\s\\S]*?)\`;`, 'm');
  const m = source.match(re);
  if (!m) throw new Error(`Block ${name} not found in schema.ts`);
  return m[1]!;
}

function transform(sql: string): string {
  let out = sql;

  // 1. Drop the SQLite schema_meta CREATE TABLE block. Phase 1's 001_init.sql
  // already created the Postgres equivalent (oracle_meta) -- D4.
  out = out.replace(
    /CREATE TABLE IF NOT EXISTS schema_meta \([\s\S]*?\);\s*/g,
    '',
  );

  // 2. INTEGER PRIMARY KEY (SQLite auto-increment) -> BIGINT GENERATED BY
  // DEFAULT AS IDENTITY PRIMARY KEY (Postgres modern equivalent).
  out = out.replace(
    /\bid +INTEGER PRIMARY KEY\b/g,
    'id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
  );

  // 3. FK to entities.id widens to BIGINT to match the new PK type.
  // Matches `entity_id INTEGER` and `predecessor_id INTEGER` regardless of
  // NOT NULL / REFERENCES suffix.
  out = out.replace(
    /\b(entity_id|predecessor_id) +INTEGER\b/g,
    '$1 BIGINT',
  );

  // 4. Boolean column conversions. Apply per allowlist column name. The
  // NOT NULL DEFAULT 0 form maps to NOT NULL DEFAULT FALSE; nullable
  // INTEGER (no constraint) maps to nullable BOOLEAN.
  for (const col of BOOLEAN_COLUMN_NAMES) {
    out = out.replace(
      new RegExp(`\\b${col} +INTEGER NOT NULL DEFAULT 0`, 'g'),
      `${col} BOOLEAN NOT NULL DEFAULT FALSE`,
    );
    out = out.replace(
      // Negative lookahead so the NOT NULL DEFAULT 0 form (already handled)
      // doesn't double-match.
      new RegExp(`\\b${col} +INTEGER\\b(?!\\s+NOT NULL)`, 'g'),
      `${col} BOOLEAN`,
    );
  }

  // 5. *_json TEXT -> *_json JSONB. Preserves any NOT NULL / DEFAULT clause
  // that follows the type. Postgres JSONB accepts the SQLite default '{}'
  // as a valid empty object.
  out = out.replace(
    /\b([a-z_]+_json) +TEXT\b/g,
    '$1 JSONB',
  );

  // 6. Timestamp columns: TEXT -> TIMESTAMPTZ. ISO 8601 strings parse
  // without explicit cast.
  for (const col of TIMESTAMP_COLUMN_NAMES) {
    out = out.replace(
      new RegExp(`\\b${col} +TEXT\\b`, 'g'),
      `${col} TIMESTAMPTZ`,
    );
  }

  // 7. SQLite `COLLATE NOCASE` index modifier -> Postgres functional index
  // on lower(col). Loader queries that match these indexes will need to
  // wrap the column in lower(...) too; see load-gameplay.ts queries.
  out = out.replace(
    /\bON ([a-z_]+)\s*\(([a-z_]+) +COLLATE NOCASE\)/g,
    'ON $1 (lower($2))',
  );

  return out;
}

function main(): void {
  const source = readFileSync(SCHEMA_TS_PATH, 'utf8');
  const blocks = BLOCK_NAMES.map((name) => ({
    name,
    sql: extractBlock(source, name),
  }));

  const banner = `-- apps/qw-oracle/db/migrations/002_layer1_schema.sql
--
-- Generator-emitted from scripts/load-knowledge/schema.ts via
-- scripts/generate-pg-migration.ts (Phase 2 of Arc 1).
--
-- DO NOT EDIT THIS FILE. Schema evolution post-Arc-1 happens via
-- append-only migrations under db/migrations/. If a dialect transform
-- is wrong, fix it in the generator and regenerate before ship.
--
-- 30 tables emitted. Source blocks (SQLite source-of-truth, concatenated
-- and dialect-transformed): SCHEMA_V1_SQL plus the V2/V3/V4/V5/V6/V12/V13/V14/V15
-- additions blocks. Migration blocks (ENTITIES_V*_MIGRATION_SQL etc.)
-- are NOT used -- the additions blocks already carry the final widened shape.
--
-- The 31st Layer 1 / metadata table (oracle_meta) ships in Phase 1's
-- migration 001_init.sql. The migrator's own bookkeeping table
-- (schema_migrations) and the embedding-model metadata table
-- (embedding_metadata) also ship in 001_init.sql.
`;

  let combined = '';
  for (const { name, sql } of blocks) {
    combined += `\n-- ===== ${name} =====\n` + sql;
  }

  const transformed = transform(combined);

  process.stdout.write(banner + transformed);
}

if (import.meta.main) {
  main();
}
