#!/bin/bash
# Generates version.js with git commit hash and build timestamp
# Run: ./scripts/generate-version.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# Get git commit hash (short)
COMMIT_HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")

# Build timestamp (YYYYMMDD-HHMM in local time)
TIMESTAMP=$(date +"%Y%m%d-%H%M")

cat > "$PROJECT_DIR/public/js/version.js" << EOF
// Auto-generated by scripts/generate-version.sh - DO NOT EDIT
window.APP_VERSION = '${COMMIT_HASH}';
window.APP_BUILD_TIME = '${TIMESTAMP}';
EOF

echo "Generated version.js: ${COMMIT_HASH} (${TIMESTAMP})"
