#!/usr/bin/env node
/**
 * Generates version.js with git commit hash and build timestamp
 * Run: node scripts/generate-version.js
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

// Change to project root directory first
const projectRoot = path.join(__dirname, '..');
process.chdir(projectRoot);

// Get git commit hash (short)
let commitHash = 'unknown';
try {
    commitHash = execSync('git rev-parse --short HEAD', {
        encoding: 'utf-8',
        cwd: projectRoot
    }).trim();
} catch (e) {
    console.warn('Could not get git commit hash:', e.message);
}

// Build timestamp (YYYYMMDD-HHMM)
const now = new Date();
const timestamp = now.toISOString().slice(0, 16).replace(/[-:T]/g, '').replace(/(\d{8})(\d{4})/, '$1-$2');

// Version string: commit hash
const version = commitHash;

const content = `// Auto-generated by scripts/generate-version.js - DO NOT EDIT
window.APP_VERSION = '${version}';
window.APP_BUILD_TIME = '${timestamp}';
`;

const outputPath = path.join(projectRoot, 'public/js/version.js');
fs.writeFileSync(outputPath, content);

console.log(`Generated version.js: ${version} (${timestamp})`);
