-- apps/qw-oracle/db/migrations/002_layer1_schema.sql
--
-- Generator-emitted from scripts/load-knowledge/schema.ts via
-- scripts/generate-pg-migration.ts (Phase 2 of Arc 1).
--
-- DO NOT EDIT THIS FILE. Schema evolution post-Arc-1 happens via
-- append-only migrations under db/migrations/. If a dialect transform
-- is wrong, fix it in the generator and regenerate before ship.
--
-- 30 tables emitted. Source blocks (SQLite source-of-truth, concatenated
-- and dialect-transformed): SCHEMA_V1_SQL plus the V2/V3/V4/V5/V6/V12/V13/V14/V15
-- additions blocks. Migration blocks (ENTITIES_V*_MIGRATION_SQL etc.)
-- are NOT used -- the additions blocks already carry the final widened shape.
--
-- The 31st Layer 1 / metadata table (oracle_meta) ships in Phase 1's
-- migration 001_init.sql. The migrator's own bookkeeping table
-- (schema_migrations) and the embedding-model metadata table
-- (embedding_metadata) also ship in 001_init.sql.

-- ===== SCHEMA_V1_SQL =====

-- Ordinal scheme: semver-encoded for tagged releases (3.6.1 -> 361,
-- 3.6.6 -> 366, etc.) so '<' on ordinal mirrors release-time order.
-- 'head' uses the sentinel HEAD_ORDINAL (999999) because it always represents
-- the dev tip, after every tagged release. All first_seen / last_seen
-- comparisons rely on this ordering. New release tags get an ordinal
-- derived from their semver; never reuse 999999 for anything else.
CREATE TABLE IF NOT EXISTS versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project        TEXT NOT NULL CHECK (project IN ('ezquake','fte','mvdsv','ktx','qwcl')),
  version        TEXT NOT NULL,
  commit_sha     TEXT NOT NULL,
  tag_date TIMESTAMPTZ,
  ordinal        INTEGER NOT NULL,
  parse_state    TEXT NOT NULL DEFAULT 'ok' CHECK (parse_state IN ('ok','partial')),
  notes          TEXT,
  extracted_at TIMESTAMPTZ NOT NULL,
  UNIQUE (project, version)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_versions_ordinal ON versions(project, ordinal);

-- The entities.type CHECK lists the full v15 type set (not just v1's four)
-- because applySchema stamps SCHEMA_VERSION directly on fresh DBs and skips
-- the migration chain. Migrated DBs rebuild this table via
-- ENTITIES_V2/V3/V5/V12/V15_MIGRATION_SQL, so the widened v1 CHECK is harmless
-- for them and correct for fresh ones. Keep this list in sync with
-- ENTITIES_V15_MIGRATION_SQL (and any future ENTITIES_V*_MIGRATION_SQL).
CREATE TABLE IF NOT EXISTS entities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project               TEXT NOT NULL CHECK (project IN ('ezquake','fte','mvdsv','ktx','qwcl')),
  type                  TEXT NOT NULL CHECK (type IN (
                          'cvar','command','macro','cmdline_param',
                          'keyname','hud_element','ruleset','token_primitive',
                          'asset_category','flag_bit','cvar_alias',
                          'protocol_message','info_key','log_template','qc_builtin'
                        )),
  name                  TEXT NOT NULL,
  canonical_id          TEXT NOT NULL,
  first_seen_version    TEXT NOT NULL,
  last_seen_version     TEXT NOT NULL,
  source_state          TEXT NOT NULL DEFAULT 'source_backed'
                          CHECK (source_state IN ('source_backed','source_retired','doc_only','dynamically_registered')),
  predecessor_id BIGINT REFERENCES entities(id),
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  UNIQUE (project, type, name),
  UNIQUE (canonical_id)
);
CREATE INDEX IF NOT EXISTS idx_entities_name ON entities(name);
CREATE INDEX IF NOT EXISTS idx_entities_type ON entities(project, type);

CREATE TABLE IF NOT EXISTS cvar_versions (
  entity_id BIGINT NOT NULL REFERENCES entities(id),
  version                 TEXT NOT NULL,
  help_desc               TEXT,
  help_remarks            TEXT,
  help_values             TEXT,
  help_group_id           TEXT,
  help_type               TEXT,
  default_value           TEXT,
  flags_raw               TEXT,
  flag_names              TEXT,
  on_change               TEXT,
  min_bound               TEXT,
  max_bound               TEXT,
  source_file             TEXT,
  source_line             INTEGER,
  source_column           INTEGER,
  storage_class           TEXT,
  group_name_in_source    TEXT,
  trailing_comment        TEXT,
  server_only BOOLEAN NOT NULL DEFAULT FALSE,
  raw_ast_hash            TEXT,
  -- v11: which source root the entity came from when the project has multiple
  -- sources (e.g., FTE engine + plugins). NULL = backwards compat for pre-v11
  -- rows; semantically equivalent to "engine".
  source_root             TEXT,
  extracted_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (entity_id, version)
);
CREATE INDEX IF NOT EXISTS idx_cvar_versions_source ON cvar_versions(source_file, source_line);

CREATE TABLE IF NOT EXISTS command_versions (
  entity_id BIGINT NOT NULL REFERENCES entities(id),
  version           TEXT NOT NULL,
  help_desc         TEXT,
  help_remarks      TEXT,
  help_group_id     TEXT,
  handler_fn        TEXT,
  source_file       TEXT,
  source_line       INTEGER,
  source_column     INTEGER,
  registration_file TEXT,
  raw_ast_hash      TEXT,
  source_root       TEXT,  -- v11: see cvar_versions.source_root comment
  extracted_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (entity_id, version)
);

CREATE TABLE IF NOT EXISTS macro_versions (
  entity_id BIGINT NOT NULL REFERENCES entities(id),
  version              TEXT NOT NULL,
  help_desc            TEXT,
  macro_type           TEXT,
  teamplay_restricted BOOLEAN NOT NULL DEFAULT FALSE,
  related_cvars_json JSONB,
  handler_fn           TEXT,
  source_file          TEXT,
  source_line          INTEGER,
  source_column        INTEGER,
  registration_file    TEXT,
  raw_ast_hash         TEXT,
  source_root          TEXT,  -- v11: see cvar_versions.source_root comment
  extracted_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (entity_id, version)
);

CREATE TABLE IF NOT EXISTS cmdline_param_versions (
  entity_id BIGINT NOT NULL REFERENCES entities(id),
  version          TEXT NOT NULL,
  help_desc        TEXT,
  help_remarks     TEXT,
  arguments        TEXT,
  flags_json JSONB,
  systems_json JSONB,
  source_file      TEXT,
  source_line      INTEGER,
  source_column    INTEGER,
  raw_ast_hash     TEXT,
  extracted_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (entity_id, version)
);

CREATE TABLE IF NOT EXISTS change_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_id BIGINT NOT NULL REFERENCES entities(id),
  from_version             TEXT,
  to_version               TEXT NOT NULL,
  change_kind              TEXT NOT NULL CHECK (change_kind IN ('created','modified','deleted')),
  field_name               TEXT NOT NULL DEFAULT '',
  old_value                TEXT,
  new_value                TEXT,
  commit_sha               TEXT NOT NULL,
  commit_message_excerpt   TEXT,
  pr_number                INTEGER,
  pr_title                 TEXT,
  pr_body_excerpt          TEXT,
  linked_issues_json JSONB,
  enrichment_source        TEXT CHECK (enrichment_source IN ('git','github_api')),
  extracted_at TIMESTAMPTZ NOT NULL,
  UNIQUE (entity_id, to_version, field_name, change_kind)
);
CREATE INDEX IF NOT EXISTS idx_change_events_to_version    ON change_events(to_version);
CREATE INDEX IF NOT EXISTS idx_change_events_entity_field  ON change_events(entity_id, field_name);
CREATE INDEX IF NOT EXISTS idx_change_events_commit        ON change_events(commit_sha);

CREATE TABLE IF NOT EXISTS source_state_transitions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_id BIGINT NOT NULL REFERENCES entities(id),
  from_state         TEXT NOT NULL,
  to_state           TEXT NOT NULL,
  reason             TEXT NOT NULL CHECK (reason IN (
                       'initial_observation',
                       'removed_from_head',
                       're_added',
                       'backfill_match',
                       'source_retired_at_version',
                       'manual_update'
                     )),
  version_context    TEXT,
  extractor_run_id   TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_sst_entity ON source_state_transitions(entity_id);
CREATE INDEX IF NOT EXISTS idx_sst_run    ON source_state_transitions(extractor_run_id);

-- ===== SCHEMA_V2_ADDITIONS_SQL =====

CREATE TABLE IF NOT EXISTS keyname_versions (
  entity_id BIGINT NOT NULL REFERENCES entities(id),
  version           TEXT NOT NULL,
  key_code          INTEGER,
  key_code_ident    TEXT,
  source_file       TEXT,
  source_line       INTEGER,
  source_column     INTEGER,
  build_variant     TEXT,
  raw_ast_hash      TEXT,
  extracted_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (entity_id, version)
);

CREATE TABLE IF NOT EXISTS hud_element_versions (
  entity_id BIGINT NOT NULL REFERENCES entities(id),
  version             TEXT NOT NULL,
  help_desc           TEXT,
  hud_alias           TEXT,
  flags_raw           TEXT,
  min_state_raw       TEXT,
  draw_order_raw      TEXT,
  draw_fn             TEXT,
  enclosing_function  TEXT,
  source_file         TEXT,
  source_line         INTEGER,
  source_column       INTEGER,
  owned_cvars_json JSONB,
  raw_ast_hash        TEXT,
  extracted_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (entity_id, version)
);

CREATE TABLE IF NOT EXISTS ruleset_versions (
  entity_id BIGINT NOT NULL REFERENCES entities(id),
  version              TEXT NOT NULL,
  enum_ident           TEXT,
  loader_fn            TEXT,
  maxfps               REAL,
  restrict_triggers BOOLEAN,
  restrict_packet BOOLEAN,
  restrict_particles BOOLEAN,
  restrict_play BOOLEAN,
  restrict_logging BOOLEAN,
  restrict_rollangle BOOLEAN,
  restrict_ipc BOOLEAN,
  restrict_exec BOOLEAN,
  restrict_setcalc BOOLEAN,
  restrict_seteval BOOLEAN,
  restrict_setex BOOLEAN,
  locked_cvars_json JSONB,
  source_file          TEXT,
  source_line          INTEGER,
  raw_ast_hash         TEXT,
  extracted_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (entity_id, version)
);

CREATE TABLE IF NOT EXISTS token_primitive_versions (
  entity_id BIGINT NOT NULL REFERENCES entities(id),
  version        TEXT NOT NULL,
  form           TEXT,
  suffix_char    TEXT,
  byte_value     INTEGER,
  category       TEXT,
  case_style     TEXT,
  source_file    TEXT,
  source_line    INTEGER,
  raw_ast_hash   TEXT,
  extracted_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (entity_id, version)
);

-- ===== SCHEMA_V3_ADDITIONS_SQL =====

CREATE TABLE IF NOT EXISTS asset_category_versions (
  entity_id BIGINT NOT NULL REFERENCES entities(id),
  version         TEXT NOT NULL,
  display_name    TEXT NOT NULL,
  description     TEXT,
  notes           TEXT,
  raw_ast_hash    TEXT,
  extracted_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (entity_id, version)
);

CREATE TABLE IF NOT EXISTS asset_extensions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project                TEXT NOT NULL CHECK (project IN ('ezquake','fte','mvdsv','ktx','qwcl')),
  version                TEXT NOT NULL,
  extension              TEXT NOT NULL,
  path_hint              TEXT,
  category_id            TEXT NOT NULL REFERENCES entities(canonical_id),
  notes                  TEXT,
  -- v7: per-row verification audit. Lifts the .kmap / .dll prose stamps from
  -- entity-types.md into a queryable column so the future review skill (and
  -- consumers like the dir-browser) can filter by hygiene status without
  -- parsing markdown. Values mirror the four buckets documented in
  -- apps/qw-oracle/docs/entity-types.md § Verification statuses.
  verification_status    TEXT NOT NULL DEFAULT 'ast_verified' CHECK (verification_status IN (
                           'ast_verified',
                           'seed_only_with_ast_support',
                           'seed_only_no_ast_support',
                           'orphaned_historical'
                         )),
  verification_reason    TEXT,
  raw_ast_hash           TEXT,
  extracted_at TIMESTAMPTZ NOT NULL,
  UNIQUE (project, version, extension, path_hint)
);
CREATE INDEX IF NOT EXISTS idx_asset_ext_cat ON asset_extensions(category_id);
CREATE INDEX IF NOT EXISTS idx_asset_ext_verif ON asset_extensions(verification_status);

CREATE TABLE IF NOT EXISTS asset_path_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project          TEXT NOT NULL CHECK (project IN ('ezquake','fte','mvdsv','ktx','qwcl')),
  version          TEXT NOT NULL,
  canonical_id     TEXT NOT NULL,
  rule_kind        TEXT NOT NULL CHECK (rule_kind IN (
                     'search_path','archive_precedence','cmdline_override','gamedir_behavior'
                   )),
  ordinal          INTEGER NOT NULL,
  description      TEXT NOT NULL,
  source_ref       TEXT,
  source_verified BOOLEAN NOT NULL DEFAULT FALSE,
  notes            TEXT,
  raw_ast_hash     TEXT,
  extracted_at TIMESTAMPTZ NOT NULL,
  UNIQUE (project, version, canonical_id)
);

CREATE TABLE IF NOT EXISTS asset_cvar_bindings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project            TEXT NOT NULL CHECK (project IN ('ezquake','fte','mvdsv','ktx','qwcl')),
  version            TEXT NOT NULL,
  cvar_canonical_id  TEXT NOT NULL REFERENCES entities(canonical_id),
  category_id        TEXT NOT NULL REFERENCES entities(canonical_id),
  path_pattern       TEXT,
  load_trigger       TEXT NOT NULL CHECK (load_trigger IN (
                       'startup','on_demand','on_connect','on_map_load','unknown'
                     )),
  confidence         TEXT NOT NULL CHECK (confidence IN (
                       'seed','auto','auto_confirms_seed','auto_orphan'
                     )),
  source_ref         TEXT,
  notes              TEXT,
  raw_ast_hash       TEXT,
  extracted_at TIMESTAMPTZ NOT NULL,
  UNIQUE (project, version, cvar_canonical_id, category_id, path_pattern)
);
CREATE INDEX IF NOT EXISTS idx_asset_cvar_bind_cvar ON asset_cvar_bindings(cvar_canonical_id);
CREATE INDEX IF NOT EXISTS idx_asset_cvar_bind_cat  ON asset_cvar_bindings(category_id);

CREATE TABLE IF NOT EXISTS asset_loader_sites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project            TEXT NOT NULL CHECK (project IN ('ezquake','fte','mvdsv','ktx','qwcl')),
  version            TEXT NOT NULL,
  canonical_id       TEXT NOT NULL,
  function_name      TEXT NOT NULL,
  source_file        TEXT NOT NULL,
  source_line        INTEGER NOT NULL,
  source_column      INTEGER,
  enclosing_function TEXT,
  reads_category_id  TEXT REFERENCES entities(canonical_id),
  load_trigger       TEXT NOT NULL CHECK (load_trigger IN (
                       'startup','on_demand','on_connect','on_map_load','unknown'
                     )),
  path_source        TEXT NOT NULL CHECK (path_source IN ('literal','cvar','computed','unknown')),
  path_literal       TEXT,
  path_cvar_id       TEXT REFERENCES entities(canonical_id),
  confidence         TEXT NOT NULL CHECK (confidence IN ('certain','heuristic','intentionally_generic','unclassified')),
  dev_only BOOLEAN NOT NULL DEFAULT FALSE,
  notes              TEXT,
  raw_ast_hash       TEXT,
  extracted_at TIMESTAMPTZ NOT NULL,
  UNIQUE (project, version, canonical_id)
);
CREATE INDEX IF NOT EXISTS idx_asset_loader_category ON asset_loader_sites(reads_category_id);
CREATE INDEX IF NOT EXISTS idx_asset_loader_cvar     ON asset_loader_sites(path_cvar_id);
CREATE INDEX IF NOT EXISTS idx_asset_loader_fn       ON asset_loader_sites(function_name);

-- ===== SCHEMA_V4_ADDITIONS_SQL =====

CREATE TABLE IF NOT EXISTS release_notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project                     TEXT NOT NULL CHECK (project IN ('ezquake','fte','mvdsv','ktx','qwcl')),
  version                     TEXT NOT NULL,
  section                     TEXT NOT NULL,
  ordinal                     INTEGER NOT NULL,
  body_md                     TEXT NOT NULL,
  referenced_entity_ids_json JSONB,
  commit_urls_json JSONB,
  pr_numbers_json JSONB,
  author_handles_json JSONB,
  raw_body_hash               TEXT,
  extracted_at TIMESTAMPTZ NOT NULL,
  UNIQUE (project, version, section, ordinal)
);
CREATE INDEX IF NOT EXISTS idx_release_notes_version ON release_notes(project, version);

-- ===== SCHEMA_V5_ADDITIONS_SQL =====

CREATE TABLE IF NOT EXISTS flag_bit_versions (
  entity_id BIGINT NOT NULL REFERENCES entities(id),
  version           TEXT NOT NULL,
  bitmask_family    TEXT NOT NULL,
  value_raw         TEXT,
  value_numeric     INTEGER,
  source_file       TEXT,
  source_line       INTEGER,
  raw_ast_hash      TEXT,
  extracted_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (entity_id, version)
);
CREATE INDEX IF NOT EXISTS idx_flag_bit_versions_family ON flag_bit_versions(bitmask_family);

CREATE TABLE IF NOT EXISTS relation_changes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  relation_table           TEXT NOT NULL CHECK (relation_table IN (
                             'asset_extensions','asset_path_rules',
                             'asset_cvar_bindings','asset_loader_sites'
                           )),
  project                  TEXT NOT NULL CHECK (project IN ('ezquake','fte','mvdsv','ktx','qwcl')),
  from_version             TEXT,
  to_version               TEXT NOT NULL,
  change_kind              TEXT NOT NULL CHECK (change_kind IN ('created','modified','deleted')),
  row_key_json JSONB NOT NULL,
  field_name               TEXT NOT NULL DEFAULT '',
  old_value                TEXT,
  new_value                TEXT,
  commit_sha               TEXT NOT NULL,
  commit_message_excerpt   TEXT,
  extracted_at TIMESTAMPTZ NOT NULL,
  UNIQUE (relation_table, project, to_version, row_key_json, field_name, change_kind)
);
CREATE INDEX IF NOT EXISTS idx_relation_changes_to_version ON relation_changes(to_version);
CREATE INDEX IF NOT EXISTS idx_relation_changes_table      ON relation_changes(relation_table);

-- ===== SCHEMA_V6_ADDITIONS_SQL =====

CREATE TABLE IF NOT EXISTS source_overrides (
  entity_id BIGINT NOT NULL REFERENCES entities(id),
  version       TEXT NOT NULL,
  field_name    TEXT NOT NULL,
  source_file   TEXT NOT NULL,
  source_line   INTEGER NOT NULL,
  source_column INTEGER,
  override_kind TEXT NOT NULL CHECK (override_kind IN (
                  'struct_field_decl',
                  'call_site',
                  'header_declaration'
                )),
  extracted_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (entity_id, version, field_name)
);
CREATE INDEX IF NOT EXISTS idx_source_overrides_entity ON source_overrides(entity_id, version);

-- ===== SCHEMA_V12_ADDITIONS_SQL =====

CREATE TABLE IF NOT EXISTS cvar_alias_versions (
  entity_id BIGINT NOT NULL REFERENCES entities(id),
  version                         TEXT NOT NULL,
  target_project                  TEXT NOT NULL CHECK (target_project IN ('ezquake','fte','mvdsv','ktx','qwcl')),
  target_kind                     TEXT NOT NULL CHECK (target_kind IN (
                                    'cvar','command','macro','serverinfo','userinfo'
                                  )),
  target_name                     TEXT NOT NULL,
  target_canonical_id             TEXT REFERENCES entities(canonical_id),
  mimics_project                  TEXT CHECK (mimics_project IN ('ezquake','fte','mvdsv','ktx','qwcl')),
  value_transform                 TEXT NOT NULL DEFAULT 'identity'
                                    CHECK (value_transform IN (
                                      'identity','bool_flip','scale','enum_remap','needs_review'
                                    )),
  value_transform_params_json JSONB,
  default_drift_status            TEXT NOT NULL DEFAULT 'unknown'
                                    CHECK (default_drift_status IN (
                                      'same','differ_safe','differ_dangerous','unknown'
                                    )),
  semantic_confidence             TEXT NOT NULL DEFAULT 'needs_review'
                                    CHECK (semantic_confidence IN (
                                      'high','medium','low','needs_review'
                                    )),
  verified_target_version         TEXT,
  verified_mimics_version         TEXT,
  freshness_state                 TEXT NOT NULL DEFAULT 'alive'
                                    CHECK (freshness_state IN (
                                      'alive','target_gone','mimics_lhs_gone','both_gone','unknown'
                                    )),
  source_file                     TEXT,
  source_line                     INTEGER,
  source_column                   INTEGER,
  source_root                     TEXT,
  raw_ast_hash                    TEXT,
  extracted_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (entity_id, version)
);
CREATE INDEX IF NOT EXISTS idx_cvar_alias_versions_target
  ON cvar_alias_versions(target_project, target_kind, target_name);
CREATE INDEX IF NOT EXISTS idx_cvar_alias_versions_canonical
  ON cvar_alias_versions(target_canonical_id);

-- ===== SCHEMA_V13_ADDITIONS_SQL =====

CREATE TABLE IF NOT EXISTS maps (
  canonical_name           TEXT PRIMARY KEY,
  file_name                TEXT NOT NULL,
  display_name             TEXT,
  author                   TEXT,
  bsp_version              TEXT NOT NULL,
  bsp_size_bytes           INTEGER NOT NULL,
  bsp_sha256               TEXT NOT NULL,
  worldspawn_json JSONB NOT NULL,
  entity_count             INTEGER NOT NULL,
  class_counts_json JSONB NOT NULL,
  item_summary_json JSONB NOT NULL,
  spawn_summary_json JSONB NOT NULL,
  features_json JSONB NOT NULL,
  wads_referenced_json JSONB NOT NULL,
  inferred_gamemodes_json JSONB NOT NULL,
  popularity_total         INTEGER,
  popularity_by_mode_json JSONB,
  popularity_rank          INTEGER,
  notes                    TEXT,
  source_bsp_url           TEXT NOT NULL,
  extracted_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_maps_popularity_rank ON maps(popularity_rank);
CREATE INDEX IF NOT EXISTS idx_maps_author          ON maps(author);

-- ===== SCHEMA_V14_ADDITIONS_SQL =====

CREATE TABLE IF NOT EXISTS gameplay_sources (
  id           TEXT PRIMARY KEY,
  display_name TEXT NOT NULL,
  description  TEXT NOT NULL,
  source_root  TEXT NOT NULL,
  notes        TEXT
);

CREATE TABLE IF NOT EXISTS gameplay_entity_defs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gameplay_source_id     TEXT NOT NULL REFERENCES gameplay_sources(id),
  kind                   TEXT NOT NULL CHECK (kind IN ('item','weapon','projectile')),
  name                   TEXT NOT NULL,
  classname              TEXT,
  damage                 REAL,
  splash_damage          REAL,
  splash_radius          REAL,
  refire_seconds         REAL,
  respawn_seconds        REAL,
  pickup_amount          REAL,
  max_carry              REAL,
  duration_seconds       REAL,
  ruleset_gate_json JSONB NOT NULL DEFAULT '{}',
  source_ref             TEXT NOT NULL,
  props_json JSONB NOT NULL DEFAULT '{}',
  notes                  TEXT,
  UNIQUE (gameplay_source_id, kind, name, ruleset_gate_json)
);
CREATE INDEX IF NOT EXISTS idx_gameplay_entity_defs_kind  ON gameplay_entity_defs(kind);
CREATE INDEX IF NOT EXISTS idx_gameplay_entity_defs_name  ON gameplay_entity_defs (lower(name));
CREATE INDEX IF NOT EXISTS idx_gameplay_entity_defs_class ON gameplay_entity_defs(classname);

CREATE TABLE IF NOT EXISTS gameplay_mechanics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gameplay_source_id     TEXT NOT NULL REFERENCES gameplay_sources(id),
  kind                   TEXT NOT NULL CHECK (kind IN (
                            'constant','env_hazard','player_stat',
                            'powerup_behavior','armor_model','death_rule',
                            'spawn_rule','dm_mode_rule'
                         )),
  name                   TEXT NOT NULL,
  value_numeric          REAL,
  value_text             TEXT,
  ruleset_gate_json JSONB NOT NULL DEFAULT '{}',
  source_ref             TEXT NOT NULL,
  props_json JSONB NOT NULL DEFAULT '{}',
  notes                  TEXT,
  UNIQUE (gameplay_source_id, kind, name, ruleset_gate_json)
);
CREATE INDEX IF NOT EXISTS idx_gameplay_mechanics_kind ON gameplay_mechanics(kind);
CREATE INDEX IF NOT EXISTS idx_gameplay_mechanics_name ON gameplay_mechanics (lower(name));

-- ===== SCHEMA_V15_ADDITIONS_SQL =====

CREATE TABLE IF NOT EXISTS protocol_message_versions (
  entity_id BIGINT NOT NULL REFERENCES entities(id),
  version          TEXT NOT NULL,
  kind             TEXT NOT NULL CHECK (kind IN (
                     'svc','clc','nq',
                     'pext_fte_bit','pext_fte_const','pext_fte_alias','pext_fte_marker',
                     'pext_mvd_bit','pext_mvd_const','pext_mvd_alias','pext_mvd_marker',
                     'protocol_version','protocol_extension_id'
                   )),
  value            TEXT,
  value_kind       TEXT,
  source_file      TEXT,
  source_line      INTEGER,
  trailing_comment TEXT,
  raw_ast_hash     TEXT,
  source_root      TEXT,
  extracted_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (entity_id, version)
);
CREATE INDEX IF NOT EXISTS idx_protocol_message_versions_source ON protocol_message_versions(source_file, source_line);

CREATE TABLE IF NOT EXISTS info_key_versions (
  entity_id BIGINT NOT NULL REFERENCES entities(id),
  version             TEXT NOT NULL,
  scope               TEXT NOT NULL CHECK (scope IN ('userinfo','serverinfo','localinfo')),
  operations          TEXT,
  source_file         TEXT,
  source_line         INTEGER,
  containing_function TEXT,
  call_sites_json JSONB,
  raw_ast_hash        TEXT,
  source_root         TEXT,
  extracted_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (entity_id, version)
);
CREATE INDEX IF NOT EXISTS idx_info_key_versions_source ON info_key_versions(source_file, source_line);

CREATE TABLE IF NOT EXISTS log_template_versions (
  entity_id BIGINT NOT NULL REFERENCES entities(id),
  version                  TEXT NOT NULL,
  channel                  TEXT NOT NULL CHECK (channel IN ('broadcast','client','console','system')),
  format_string            TEXT NOT NULL,
  format_string_normalized TEXT NOT NULL,
  source_file              TEXT,
  source_line              INTEGER,
  containing_function      TEXT,
  -- v17 (Phase D Task 10): JSON array of every call site that registers this
  -- (channel, format_string) tuple. Pre-v17 rows store NULL; v17+ rows always
  -- carry at least one entry (the first call site). Schema parity with
  -- info_key_versions.call_sites_json.
  all_call_sites_json JSONB,
  raw_ast_hash             TEXT,
  source_root              TEXT,
  extracted_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (entity_id, version)
);
CREATE INDEX IF NOT EXISTS idx_log_template_versions_source ON log_template_versions(source_file, source_line);
CREATE INDEX IF NOT EXISTS idx_log_template_versions_channel ON log_template_versions(channel);

CREATE TABLE IF NOT EXISTS qc_builtin_versions (
  entity_id BIGINT NOT NULL REFERENCES entities(id),
  version          TEXT NOT NULL,
  table_name       TEXT NOT NULL,
  builtin_index    INTEGER NOT NULL,
  handler_fn       TEXT NOT NULL,
  qc_signature     TEXT,
  source_file      TEXT,
  source_line      INTEGER,
  trailing_comment TEXT,
  raw_ast_hash     TEXT,
  source_root      TEXT,
  extracted_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (entity_id, version)
);
CREATE INDEX IF NOT EXISTS idx_qc_builtin_versions_source ON qc_builtin_versions(source_file, source_line);
