-- apps/qw-oracle/db/migrations/004_layer2_chat.sql
-- Layer 2: Discord chat corpus. IRC excluded entirely in Arc 1 (D9-revised);
-- the platform CHECK locks to 'discord'. Future Arc 3 reconsideration of IRC
-- (after a codepage re-import is shown to be useful) is a one-line CHECK
-- widening here.
--
-- Source-of-truth shape: apps/qw-oracle/scripts/db.mjs (SQLite, retiring in
-- this phase). The 'network' column from the SQLite shape is dropped because
-- it was IRC-only ('quakenet'); without IRC there is nothing to put in it.
--
-- tsvector config is 'simple' (D7): the Discord corpus is mixed-language
-- (Swedish, Russian, German handles and snippets); English stemming would
-- mangle non-English tokens. Layer 1 entity descriptions and Layer 3 chunks
-- stay on 'english' because those are curated English content (different
-- migration files).

-- Raw messages. Per CLAUDE.md "raw is immutable", every imported row is
-- preserved intact; derived processing (sessions, message_labels,
-- session_search) is rebuildable.
CREATE TABLE messages (
  id                    TEXT PRIMARY KEY,
  platform              TEXT NOT NULL CHECK (platform = 'discord'),
  guild_id              TEXT,
  channel_name          TEXT NOT NULL,
  author_id             TEXT,
  author_name           TEXT NOT NULL,
  author_display_name   TEXT,
  author_is_bot         BOOLEAN NOT NULL DEFAULT FALSE,
  content               TEXT NOT NULL DEFAULT '',
  message_type          TEXT NOT NULL DEFAULT 'message'
                        CHECK (message_type IN ('message', 'action', 'join', 'part', 'quit',
                                                'nick', 'topic', 'system')),
  referenced_message_id TEXT,
  attachment_count      INTEGER NOT NULL DEFAULT 0,
  attachments_json      JSONB,
  embed_count           INTEGER NOT NULL DEFAULT 0,
  embeds_json           JSONB,
  reaction_count        INTEGER NOT NULL DEFAULT 0,
  reactions_json        JSONB,
  created_at            TIMESTAMPTZ NOT NULL,
  edited_at             TIMESTAMPTZ,
  source                TEXT NOT NULL,
  source_file           TEXT,
  imported_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  content_tsv           tsvector GENERATED ALWAYS AS (to_tsvector('simple', coalesce(content, ''))) STORED
);
CREATE INDEX messages_platform_created    ON messages(platform, created_at);
CREATE INDEX messages_channel_created     ON messages(channel_name, created_at);
CREATE INDEX messages_author_created      ON messages(author_name, created_at);
CREATE INDEX messages_message_type        ON messages(message_type);
CREATE INDEX messages_created             ON messages(created_at);
CREATE INDEX messages_content_tsv_gin     ON messages USING GIN (content_tsv);

-- Operator-known Discord channel metadata. Hand-seeded (see seeds/discord_channels.sql);
-- Discord exports do NOT include guild_id at message granularity, so the
-- table is populated separately rather than derived from import.
CREATE TABLE discord_channels (
  channel_name TEXT PRIMARY KEY,
  channel_id   TEXT NOT NULL,
  guild_id     TEXT NOT NULL
);

-- Per-file import bookkeeping. Used by importer to skip already-loaded files.
CREATE TABLE import_log (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_file       TEXT NOT NULL UNIQUE,
  platform          TEXT NOT NULL CHECK (platform = 'discord'),
  channel_name      TEXT,
  message_count     INTEGER NOT NULL DEFAULT 0,
  date_range_start  TIMESTAMPTZ,
  date_range_end    TIMESTAMPTZ,
  imported_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Per-version processing bookkeeping. process-tier1 used this to skip
-- re-processing when VERSION matched. Port preserves the gate.
CREATE TABLE processing_log (
  id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version                TEXT NOT NULL,
  channels_processed     INTEGER,
  sessions_created       INTEGER,
  messages_labeled       INTEGER,
  gap_threshold_minutes  INTEGER,
  started_at             TIMESTAMPTZ NOT NULL,
  finished_at            TIMESTAMPTZ
);

-- Conversation sessions: groups of messages forming a discussion, segmented
-- by gap_threshold_minutes of silence. Derived; rebuilt by build-sessions.ts.
CREATE TABLE sessions (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  channel_name        TEXT NOT NULL,
  platform            TEXT NOT NULL CHECK (platform = 'discord'),
  started_at          TIMESTAMPTZ NOT NULL,
  ended_at            TIMESTAMPTZ NOT NULL,
  message_count       INTEGER NOT NULL,
  chat_message_count  INTEGER NOT NULL,
  participant_count   INTEGER NOT NULL,
  participants_json   JSONB,
  version             TEXT NOT NULL
);
CREATE INDEX sessions_channel_started ON sessions(channel_name, started_at);
CREATE INDEX sessions_started         ON sessions(started_at);

-- Per-message classification + session assignment. Derived; rebuilt by
-- build-sessions.ts.
--
-- session_id is NULLABLE: under filter-then-segment, bot/reaction/system
-- messages never start a session, so label rows for those messages are written
-- with session_id IS NULL. Every imported message still has exactly one label
-- row; session-scoped queries simply add WHERE session_id IS NOT NULL.
CREATE TABLE message_labels (
  message_id  TEXT PRIMARY KEY REFERENCES messages(id) ON DELETE CASCADE,
  session_id  BIGINT REFERENCES sessions(id) ON DELETE CASCADE,
  category    TEXT NOT NULL CHECK (category IN ('chat', 'bot', 'reaction', 'link', 'system')),
  version     TEXT NOT NULL
);
CREATE INDEX message_labels_session   ON message_labels(session_id);
CREATE INDEX message_labels_category  ON message_labels(category);

-- Cross-session reply graph. Built post-segmentation by build-session-references.ts.
-- Each row: source session contains a message that replies to a message in
-- target session (via messages.referenced_message_id). reference_count is the
-- number of such reply edges between the pair. Within-session replies are skipped
-- (source = target). Phase 6's search_solved_issues uses this to surface related
-- sessions when the reply graph crosses a session boundary.
CREATE TABLE session_references (
  source_session_id   BIGINT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  target_session_id   BIGINT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  reference_count     INTEGER NOT NULL,
  PRIMARY KEY (source_session_id, target_session_id),
  CHECK (source_session_id <> target_session_id)
);
CREATE INDEX session_references_target ON session_references(target_session_id);

-- Concatenated chat content per session, indexed for FTS. Replaces SQLite
-- FTS5's session_search VIRTUAL TABLE. Postgres has no FTS5 analogue; we ship
-- a real table populated by build-search-index.ts (TRUNCATE + rebuild,
-- idempotent on inputs). tsvector config 'simple' per D7.
CREATE TABLE session_search (
  session_id           BIGINT PRIMARY KEY REFERENCES sessions(id) ON DELETE CASCADE,
  channel_name         TEXT NOT NULL,
  platform             TEXT NOT NULL CHECK (platform = 'discord'),
  started_at           TIMESTAMPTZ NOT NULL,
  participants         JSONB,
  chat_message_count   INTEGER NOT NULL,
  content              TEXT NOT NULL,
  session_tsv          tsvector GENERATED ALWAYS AS (to_tsvector('simple', coalesce(content, ''))) STORED
);
CREATE INDEX session_search_tsv_gin    ON session_search USING GIN (session_tsv);
CREATE INDEX session_search_channel    ON session_search(channel_name, started_at);
