-- apps/qw-oracle/db/migrations/021_layer2_threads.sql
-- Layer 2 corpus reconstruction: chat_threads + thread_messages junction.
--
-- D3: chat_threads stores reconstructed conversation threads whose `content`
-- column is the raw concatenated member messages (not a summary). That
-- verbatim content drives both FTS (content_tsv) and the semantic embedding
-- (topic_embedding), so downstream retrieval has both lexical and vector
-- recall over the original words.
--
-- D4: schema is exactly the DDL below -- no deviation from the spec. Each
-- reconstructed thread is identified by thread_key (the idempotency anchor:
-- same source data always produces the same key, so re-runs are safe upserts).
-- participant_count / message_count / topic_label are mandatory because the
-- loader can always compute them; resolution_status / buckets_question /
-- buckets_answer are nullable because they are filled by later classification
-- phases, not the reconstruction loader.
--
-- D7: tsvector config is 'simple' for the same reason as the Layer 2 messages
-- table: the Discord corpus is mixed-language (Swedish, Russian, German handles
-- and fragments). English stemming ('english') would mangle non-English tokens.
-- 'simple' tokenises without stemming and is language-agnostic. Layer 3
-- concept chunks use 'english' because that corpus is curated English content
-- (different migration files, different recall requirements).
--
-- topic_embedding: vector(1024) mirrors the concept_chunks.embedding shape
-- from 005_layer3_concepts.sql. Both use voyage-4-large embeddings at 1024
-- dimensions. The hnsw index (vector_cosine_ops) mirrors the concept_chunks
-- hnsw index for the same reason: cosine similarity is the correct metric for
-- normalised Voyage embeddings, and hnsw gives sub-linear ANN recall at query
-- time. NULL until the embedding worker fills it; embedding_stale follows the
-- same convention as concept_chunks: FALSE by default, set TRUE on Voyage API
-- failure as a retry signal.
--
-- resolution_status / buckets_question / buckets_answer ship nullable (D4):
-- they are outputs of the later LLM classification phase, not inputs to the
-- reconstruction loader. Nullable avoids a mandatory backfill on insert and
-- lets the reconstruction and classification phases run independently.
--
-- thread_messages is a many-to-many junction (D4) because one message can
-- participate in multiple reconstructed threads (e.g. a message in a cross-
-- channel reply chain, or a seed message that anchors two overlapping threads).
-- The junction lets chat_threads own the thread-level aggregate while messages
-- table retains the canonical per-message record. ON DELETE CASCADE on both
-- FKs: deleting a thread prunes its junction rows; deleting a message prunes
-- its junction rows. The separate message_id index covers the reverse lookup
-- (which threads contain this message?).

CREATE TABLE chat_threads (
  id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_key             TEXT NOT NULL UNIQUE,
  channel_name           TEXT NOT NULL,
  platform               TEXT NOT NULL CHECK (platform = 'discord'),
  date_range_start       TIMESTAMPTZ NOT NULL,
  date_range_end         TIMESTAMPTZ NOT NULL,
  participant_count      INTEGER NOT NULL,
  participants_json      JSONB,
  message_count          INTEGER NOT NULL,
  topic_label            TEXT NOT NULL,
  content                TEXT NOT NULL,
  content_tsv            tsvector GENERATED ALWAYS AS (to_tsvector('simple', coalesce(content, ''))) STORED,
  topic_embedding        vector(1024),
  embedding_stale        BOOLEAN NOT NULL DEFAULT FALSE,
  resolution_status      TEXT CHECK (resolution_status IN ('solved','unresolved','informational')),
  buckets_question       JSONB,
  buckets_answer         JSONB,
  reconstruction_version TEXT NOT NULL,
  reconstructed_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX chat_threads_channel_started ON chat_threads(channel_name, date_range_start);
CREATE INDEX chat_threads_status          ON chat_threads(resolution_status);
CREATE INDEX chat_threads_embedding_hnsw  ON chat_threads USING hnsw (topic_embedding vector_cosine_ops);
CREATE INDEX chat_threads_content_tsv_gin ON chat_threads USING GIN (content_tsv);

CREATE TABLE thread_messages (
  thread_id  BIGINT NOT NULL REFERENCES chat_threads(id) ON DELETE CASCADE,
  message_id TEXT   NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
  PRIMARY KEY (thread_id, message_id)
);
CREATE INDEX thread_messages_message ON thread_messages(message_id);
