import type { ConversionResult } from "../converter/converter.js";

/**
 * Serialize a ConversionResult to ezQuake config text.
 * Cvars and binds are sorted alphabetically.
 * Format:
 *   cvar "value"
 *   bind key "action"
 */
export function writeEzQuakeConfig(result: ConversionResult): string {
  const lines: string[] = ["// Generated by Slipgate QW Config Converter", ""];

  // Cvars — sorted alphabetically
  const sortedCvars = Array.from(result.targetCvars.entries()).sort(([a], [b]) =>
    a.localeCompare(b)
  );

  for (const [name, value] of sortedCvars) {
    lines.push(`${name} "${value}"`);
  }

  if (sortedCvars.length > 0) {
    lines.push("");
  }

  // Binds — sorted alphabetically
  const sortedBinds = Array.from(result.targetBinds.entries()).sort(([a], [b]) =>
    a.localeCompare(b)
  );

  for (const [key, action] of sortedBinds) {
    lines.push(`bind ${key} "${action}"`);
  }

  return lines.join("\n");
}
