-- docs-l1-enrichment: MVDSV categorize (291 = 183 cvar + 108 cmd) into the 14
-- locked categories. category_inferred is written to ALL version rows per
-- entity (mvdsv is head-only). Match on name_fold (lowercase) for case-safety.
-- Idempotent. Guards at the end: dup mapping, unmatched mapping, NULL category.
BEGIN;
CREATE TEMP TABLE _mv(type text, name text, cat text) ON COMMIT DROP;
INSERT INTO _mv(type,name,cat) VALUES
-- ===== Server identity & info =====
('cvar','city','Server identity & info'),
('cvar','coords','Server identity & info'),
('cvar','countrycode','Server identity & info'),
('cvar','halflifebsp','Server identity & info'),
('cvar','hostname','Server identity & info'),
('cvar','hostport','Server identity & info'),
('cvar','qws_builddate','Server identity & info'),
('cvar','qws_buildnum','Server identity & info'),
('cvar','qws_fullname','Server identity & info'),
('cvar','qws_homepage','Server identity & info'),
('cvar','qws_name','Server identity & info'),
('cvar','qws_platform','Server identity & info'),
('cvar','qws_version','Server identity & info'),
('cvar','registered','Server identity & info'),
('cvar','sv_admininfo','Server identity & info'),
('cvar','sv_bspversion','Server identity & info'),
('cvar','sv_paused','Server identity & info'),
('cvar','version','Server identity & info'),
('cvar','watervis','Server identity & info'),
('command','localinfo','Server identity & info'),
('command','serverinfo','Server identity & info'),
('command','status','Server identity & info'),
('command','sv_status','Server identity & info'),
('command','user','Server identity & info'),
-- ===== Match & game rules =====
('cvar','coop','Match & game rules'),
('cvar','deathmatch','Match & game rules'),
('cvar','fraglimit','Match & game rules'),
('cvar','maxclients','Match & game rules'),
('cvar','maxspectators','Match & game rules'),
('cvar','pausable','Match & game rules'),
('cvar','samelevel','Match & game rules'),
('cvar','skill','Match & game rules'),
('cvar','sv_cheats','Match & game rules'),
('cvar','sv_extlimits','Match & game rules'),
('cvar','sv_mapcheck','Match & game rules'),
('cvar','teamplay','Match & game rules'),
('cvar','timelimit','Match & game rules'),
('command','check_maps','Match & game rules'),
('command','devmap','Match & game rules'),
('command','give','Match & game rules'),
('command','god','Match & game rules'),
('command','load','Match & game rules'),
('command','map','Match & game rules'),
('command','noclip','Match & game rules'),
('command','save','Match & game rules'),
-- ===== Movement & physics =====
('cvar','pm_airstep','Movement & physics'),
('cvar','pm_bunnyspeedcap','Movement & physics'),
('cvar','pm_ktjump','Movement & physics'),
('cvar','pm_pground','Movement & physics'),
('cvar','pm_rampjump','Movement & physics'),
('cvar','pm_slidefix','Movement & physics'),
('cvar','sv_accelerate','Movement & physics'),
('cvar','sv_airaccelerate','Movement & physics'),
('cvar','sv_friction','Movement & physics'),
('cvar','sv_gravity','Movement & physics'),
('cvar','sv_maxpitch','Movement & physics'),
('cvar','sv_maxspeed','Movement & physics'),
('cvar','sv_maxvelocity','Movement & physics'),
('cvar','sv_minpitch','Movement & physics'),
('cvar','sv_safestrafe','Movement & physics'),
('cvar','sv_spectatormaxspeed','Movement & physics'),
('cvar','sv_stopspeed','Movement & physics'),
('cvar','sv_wateraccelerate','Movement & physics'),
('cvar','sv_waterfriction','Movement & physics'),
-- ===== Antilag =====
('cvar','sv_antilag','Antilag'),
('cvar','sv_antilag_no_pred','Antilag'),
('cvar','sv_antilag_projectiles','Antilag'),
-- ===== Network & performance =====
('cvar','maxfps','Network & performance'),
('cvar','sv_bigcoords','Network & performance'),
('cvar','sv_enable_cmd_minping','Network & performance'),
('cvar','sv_getrealip','Network & performance'),
('cvar','sv_idlesleep','Network & performance'),
('cvar','sv_local_addr','Network & performance'),
('cvar','sv_maxping','Network & performance'),
('cvar','sv_maxrate','Network & performance'),
('cvar','sv_maxtic','Network & performance'),
('cvar','sv_minping','Network & performance'),
('cvar','sv_mintic','Network & performance'),
('cvar','sv_nailhack','Network & performance'),
('cvar','sv_phs','Network & performance'),
('cvar','sv_reconnectlimit','Network & performance'),
('cvar','sv_reliable_sound','Network & performance'),
('cvar','sv_serverip','Network & performance'),
('cvar','sv_use_dns','Network & performance'),
('cvar','sys_select_timeout','Network & performance'),
('cvar','sys_sleep','Network & performance'),
('cvar','timeout','Network & performance'),
('cvar','zombietime','Network & performance'),
('command','heartbeat','Network & performance'),
('command','nslookup','Network & performance'),
('command','setmaster','Network & performance'),
-- ===== Accounts & authentication =====
('cvar','password','Accounts & authentication'),
('cvar','rcon_password','Accounts & authentication'),
('cvar','spectator_password','Accounts & authentication'),
('cvar','sv_crypt_rcon','Accounts & authentication'),
('cvar','sv_forcenick','Accounts & authentication'),
('cvar','sv_hashpasswords','Accounts & authentication'),
('cvar','sv_login','Accounts & authentication'),
('cvar','sv_login_web','Accounts & authentication'),
('cvar','sv_rconlim','Accounts & authentication'),
('cvar','sv_registrationinfo','Accounts & authentication'),
('command','acc_block','Accounts & authentication'),
('command','acc_create','Accounts & authentication'),
('command','acc_list','Accounts & authentication'),
('command','acc_remove','Accounts & authentication'),
('command','acc_unblock','Accounts & authentication'),
('command','master_rcon_password','Accounts & authentication'),
-- ===== Access control & VIP =====
('cvar','filterban','Access control & VIP'),
('cvar','maxvip_spectators','Access control & VIP'),
('cvar','vip_password','Access control & VIP'),
('cvar','vip_values','Access control & VIP'),
('command','addip','Access control & VIP'),
('command','listip','Access control & VIP'),
('command','removeip','Access control & VIP'),
('command','vip_addip','Access control & VIP'),
('command','vip_listip','Access control & VIP'),
('command','vip_removeip','Access control & VIP'),
('command','vip_writeip','Access control & VIP'),
('command','writeip','Access control & VIP'),
-- ===== Admin & moderation =====
('cvar','sv_default_name','Admin & moderation'),
('cvar','sv_forcespec_onfull','Admin & moderation'),
('cvar','sv_kicktop','Admin & moderation'),
('cvar','sv_kickuserinfospamcount','Admin & moderation'),
('cvar','sv_kickuserinfospamtime','Admin & moderation'),
('cvar','sv_sayteam_to_spec','Admin & moderation'),
('cvar','sv_specprint','Admin & moderation'),
('cvar','sv_spectalk','Admin & moderation'),
('cvar','sv_speedcheck','Admin & moderation'),
('cvar','sv_unfake','Admin & moderation'),
('command','cuff','Admin & moderation'),
('command','floodprot','Admin & moderation'),
('command','floodprotmsg','Admin & moderation'),
('command','kick','Admin & moderation'),
('command','mute','Admin & moderation'),
('command','penaltylist','Admin & moderation'),
('command','penaltyremove','Admin & moderation'),
('command','say','Admin & moderation'),
('command','snap','Admin & moderation'),
('command','snapall','Admin & moderation'),
('command','svadmin','Admin & moderation'),
-- ===== Demo recording =====
('cvar','extralogname','Demo recording'),
('cvar','serverdemo','Demo recording'),
('cvar','sv_allowlastscores','Demo recording'),
('cvar','sv_democachesize','Demo recording'),
('cvar','sv_democlearold','Demo recording'),
('cvar','sv_demodir','Demo recording'),
('cvar','sv_demodiralt','Demo recording'),
('cvar','sv_demoextranames','Demo recording'),
('cvar','sv_demofps','Demo recording'),
('cvar','sv_demoidlefps','Demo recording'),
('cvar','sv_demomaxdirsize','Demo recording'),
('cvar','sv_demomaxsize','Demo recording'),
('cvar','sv_demoprefix','Demo recording'),
('cvar','sv_demopings','Demo recording'),
('cvar','sv_demoregexp','Demo recording'),
('cvar','sv_demosuffix','Demo recording'),
('cvar','sv_demotxt','Demo recording'),
('cvar','sv_demousecache','Demo recording'),
('cvar','sv_ondemoremove','Demo recording'),
('cvar','sv_onrecordfinish','Demo recording'),
('cvar','sv_silentrecord','Demo recording'),
('command','cancel','Demo recording'),
('command','easyrecord','Demo recording'),
('command','record','Demo recording'),
('command','stop','Demo recording'),
('command','sv_democancel','Demo recording'),
('command','sv_demoeasyrecord','Demo recording'),
('command','sv_demoembedinfo','Demo recording'),
('command','sv_demoinfo','Demo recording'),
('command','sv_demoinfoadd','Demo recording'),
('command','sv_demoinforemove','Demo recording'),
('command','sv_demolist','Demo recording'),
('command','sv_demolistr','Demo recording'),
('command','sv_demolistregex','Demo recording'),
('command','sv_demonumremove','Demo recording'),
('command','sv_demorecord','Demo recording'),
('command','sv_demoremove','Demo recording'),
('command','sv_demostop','Demo recording'),
('command','sv_lastscores','Demo recording'),
-- ===== QTV, broadcast & voice =====
('cvar','qtv_maxstreams','QTV, broadcast & voice'),
('cvar','qtv_password','QTV, broadcast & voice'),
('cvar','qtv_pendingtimeout','QTV, broadcast & voice'),
('cvar','qtv_sayenabled','QTV, broadcast & voice'),
('cvar','qtv_streamport','QTV, broadcast & voice'),
('cvar','qtv_streamtimeout','QTV, broadcast & voice'),
('cvar','sv_broadcast_enabled','QTV, broadcast & voice'),
('cvar','sv_broadcast_sender_validation_enabled','QTV, broadcast & voice'),
('cvar','sv_voip','QTV, broadcast & voice'),
('cvar','sv_voip_echo','QTV, broadcast & voice'),
('cvar','sv_voip_record','QTV, broadcast & voice'),
('command','qtv_close','QTV, broadcast & voice'),
('command','qtv_list','QTV, broadcast & voice'),
('command','qtv_status','QTV, broadcast & voice'),
('command','updatebroadcasts','QTV, broadcast & voice'),
-- ===== Logging & diagnostics =====
('cvar','developer','Logging & diagnostics'),
('cvar','frag_log_type','Logging & diagnostics'),
('cvar','qconsole_log_say','Logging & diagnostics'),
('cvar','showdrop','Logging & diagnostics'),
('cvar','showpackets','Logging & diagnostics'),
('cvar','sv_debug_antilag','Logging & diagnostics'),
('cvar','sv_debug_usercmd','Logging & diagnostics'),
('cvar','sv_debug_weapons','Logging & diagnostics'),
('cvar','sv_logdir','Logging & diagnostics'),
('cvar','sv_maxlogsize','Logging & diagnostics'),
('cvar','sv_timestamplen','Logging & diagnostics'),
('cvar','sys_command_line','Logging & diagnostics'),
('cvar','sys_extrasleep','Logging & diagnostics'),
('cvar','sys_nostdout','Logging & diagnostics'),
('cvar','sys_restart_on_error','Logging & diagnostics'),
('cvar','sys_simulation','Logging & diagnostics'),
('cvar','telnet_log_level','Logging & diagnostics'),
('command','cache_print','Logging & diagnostics'),
('command','cache_report','Logging & diagnostics'),
('command','edict','Logging & diagnostics'),
('command','edictcount','Logging & diagnostics'),
('command','edicts','Logging & diagnostics'),
('command','fraglogfile','Logging & diagnostics'),
('command','hunk_print','Logging & diagnostics'),
('command','logerrors','Logging & diagnostics'),
('command','logfile','Logging & diagnostics'),
('command','logplayers','Logging & diagnostics'),
('command','logrcon','Logging & diagnostics'),
('command','logtelnet','Logging & diagnostics'),
('command','modfraglogfile','Logging & diagnostics'),
('command','profile','Logging & diagnostics'),
('command','sv_usercmdtrace','Logging & diagnostics'),
('command','vminfo','Logging & diagnostics'),
-- ===== Web & downloads =====
('cvar','allow_download','Web & downloads'),
('cvar','allow_download_demos','Web & downloads'),
('cvar','allow_download_maps','Web & downloads'),
('cvar','allow_download_models','Web & downloads'),
('cvar','allow_download_other','Web & downloads'),
('cvar','allow_download_pakmaps','Web & downloads'),
('cvar','allow_download_skins','Web & downloads'),
('cvar','allow_download_sounds','Web & downloads'),
('cvar','download_map_url','Web & downloads'),
('cvar','sv_downloadchunksperframe','Web & downloads'),
('cvar','sv_maxdownloadrate','Web & downloads'),
('cvar','sv_maxuploadsize','Web & downloads'),
('cvar','sv_www_address','Web & downloads'),
('cvar','sv_www_authkey','Web & downloads'),
('cvar','sv_www_checkin_period','Web & downloads'),
('command','sv_web_get','Web & downloads'),
('command','sv_web_post','Web & downloads'),
('command','sv_web_postfile','Web & downloads'),
-- ===== Game module & extensions =====
('cvar','pext_ezquake_verfortrans','Game module & extensions'),
('cvar','qwm_builddate','Game module & extensions'),
('cvar','qwm_buildnum','Game module & extensions'),
('cvar','qwm_fullname','Game module & extensions'),
('cvar','qwm_homepage','Game module & extensions'),
('cvar','qwm_name','Game module & extensions'),
('cvar','qwm_platform','Game module & extensions'),
('cvar','qwm_version','Game module & extensions'),
('cvar','sv_csqc_progname','Game module & extensions'),
('cvar','sv_loadentfiles','Game module & extensions'),
('cvar','sv_loadentfiles_dir','Game module & extensions'),
('cvar','sv_mod_extensions','Game module & extensions'),
('cvar','sv_mod_msg_file','Game module & extensions'),
('cvar','sv_pext_mvdsv_serversideweapon','Game module & extensions'),
('cvar','sv_pr2references','Game module & extensions'),
('cvar','sv_progsname','Game module & extensions'),
('cvar','sv_progtype','Game module & extensions'),
('cvar','sv_serveme_fix','Game module & extensions'),
('cvar','vm_rtchecks','Game module & extensions'),
('command','gamedir','Game module & extensions'),
('command','mod','Game module & extensions'),
('command','sv_gamedir','Game module & extensions'),
-- ===== Console, scripting & filesystem =====
('cvar','fs_cache','Console, scripting & filesystem'),
('command','alias','Console, scripting & filesystem'),
('command','chmod','Console, scripting & filesystem'),
('command','cmdlist','Console, scripting & filesystem'),
('command','cvardump','Console, scripting & filesystem'),
('command','cvarlist','Console, scripting & filesystem'),
('command','echo','Console, scripting & filesystem'),
('command','exec','Console, scripting & filesystem'),
('command','flush','Console, scripting & filesystem'),
('command','if','Console, scripting & filesystem'),
('command','inc','Console, scripting & filesystem'),
('command','localcommand','Console, scripting & filesystem'),
('command','ls','Console, scripting & filesystem'),
('command','path','Console, scripting & filesystem'),
('command','quit','Console, scripting & filesystem'),
('command','restart','Console, scripting & filesystem'),
('command','rm','Console, scripting & filesystem'),
('command','rmdir','Console, scripting & filesystem'),
('command','script','Console, scripting & filesystem'),
('command','set','Console, scripting & filesystem'),
('command','toggle','Console, scripting & filesystem'),
('command','unalias','Console, scripting & filesystem'),
('command','unaliasall','Console, scripting & filesystem'),
('command','wait','Console, scripting & filesystem');

UPDATE cvar_versions cv SET
  category_inferred = m.cat,
  category_inferred_origin = 'claude-opus-4-8|mvdsv-categorize-v1'
FROM entities e, _mv m
WHERE cv.entity_id=e.id AND e.project='mvdsv' AND e.type='cvar'
  AND e.name_fold=m.name AND m.type='cvar';

UPDATE command_versions cm SET
  category_inferred = m.cat,
  category_inferred_origin = 'claude-opus-4-8|mvdsv-categorize-v1'
FROM entities e, _mv m
WHERE cm.entity_id=e.id AND e.project='mvdsv' AND e.type='command'
  AND e.name_fold=m.name AND m.type='command';

-- guards
SELECT 'dup_mapping' AS check, type, name, count(*) FROM _mv GROUP BY type,name HAVING count(*)>1;
SELECT 'unmatched_mapping' AS check, m.type, m.name FROM _mv m
  WHERE NOT EXISTS (SELECT 1 FROM entities e WHERE e.project='mvdsv' AND e.type=m.type AND e.name_fold=m.name);
SELECT 'null_cat_cvar' AS check, count(*) AS n FROM entities e JOIN cvar_versions cv ON cv.entity_id=e.id
  WHERE e.project='mvdsv' AND e.type='cvar' AND cv.category_inferred IS NULL;
SELECT 'null_cat_cmd' AS check, count(*) AS n FROM entities e JOIN command_versions cm ON cm.entity_id=e.id
  WHERE e.project='mvdsv' AND e.type='command' AND cm.category_inferred IS NULL;
COMMIT;

-- distribution
SELECT cv.category_inferred, count(DISTINCT e.id) AS cvars FROM entities e
  JOIN cvar_versions cv ON cv.entity_id=e.id WHERE e.project='mvdsv' AND e.type='cvar'
  GROUP BY 1 ORDER BY 2 DESC;
SELECT cm.category_inferred, count(DISTINCT e.id) AS cmds FROM entities e
  JOIN command_versions cm ON cm.entity_id=e.id WHERE e.project='mvdsv' AND e.type='command'
  GROUP BY 1 ORDER BY 2 DESC;
