#!/usr/bin/env bash
#
# Phase 7 idempotency probe: re-run KTX extract-tag end-to-end and assert
# zero row-count drift + zero content-hash drift across every KTX-scoped
# table. Per decisions.md D15: every loader is idempotent by construction;
# bug manifests as count-inflation false positives (re-run doubles rows)
# or silent JSONB drift (stringification on second load). This script
# gates both classes.
#
# Usage:
#   bash apps/qw-oracle/scripts/extractors/ktx/idempotency-ktx.sh
#
# Exit codes:
#   0 -- idempotent (no drift across all KTX-scoped tables)
#   1 -- count drift OR content-hash drift detected; review the diff output

set -euo pipefail

# Script lives at apps/qw-oracle/scripts/extractors/ktx/ -- 5 levels deep
# from the monorepo root.
cd "$(dirname "$0")/../../../../.."

# Dev DB lives in the qw-oracle-postgres-dev docker container (per the
# project's docker-compose.dev.yml). Calling psql directly assumes the
# host has postgresql-client installed; on this dev WSL it doesn't.
# `docker exec ... psql` matches the broader project convention (see
# the npm `db:psql` script) and avoids the host-tooling dependency.
PSQL="docker exec qw-oracle-postgres-dev psql -U qworacle -d qw_oracle"

# Three table sets, each with its own scoping convention:
#   ENTITIES_TABLE: filter directly on project='ktx'.
#   VERSIONS_TABLES: join entities on entity_id, filter project='ktx'.
#   GAMEPLAY_TABLES: filter on gameplay_source_id='ktx'.
ENTITIES_TABLE="entities"
VERSIONS_TABLES=(
  cvar_versions
  command_versions
  info_key_versions
  log_template_versions
  match_event_versions
)
GAMEPLAY_TABLES=(
  gameplay_mechanics
  gameplay_entity_defs
)

# Volatile columns excluded from the snapshot row hash. These are
# refresh-on-every-load fields whose drift across re-runs is expected
# (timestamps bumped by the loader's UPSERT) or post-derive embed-
# pipeline state (the embedding triple) and would mask the actual
# data-equivalence question. Applied via to_jsonb(row) - 'key' chains;
# the `-` operator is a no-op when the key does not exist on the table,
# so a single strip list covers all 8 KTX-scoped tables.
#
# entities-only:
#   - updated_at:                   bumped to now() by every deriver UPDATE.
#   - description_embedding:        regenerated by Phase 5 if hash drifts.
#   - description_embedding_sha256: derived from description text.
#   - description_embedding_stale:  transient; flips TRUE on derive, FALSE
#                                   after embed. Stable end state but
#                                   skipped to keep the diff tight.
#
# *_versions:
#   - extracted_at: bumped by the loader's UPSERT on every re-extract,
#                   even when the row data is identical (the loader
#                   doesn't diff before writing).
#
# created_at on entities stays IN -- it's set once on insert and never
# updated; if it drifts between pre and post that signals a real
# data-shape change (row deleted + reinserted), which is exactly what
# this probe should catch.
strip_volatile() {
  local row_alias="$1"
  echo "(to_jsonb(${row_alias}) \
    - 'updated_at' \
    - 'extracted_at' \
    - 'description_embedding' \
    - 'description_embedding_sha256' \
    - 'description_embedding_stale')"
}

snapshot() {
  local label="$1"
  local outfile="/tmp/ktx-idempotency-${label}.txt"
  : > "$outfile"

  local strip_t strip_v strip_g
  strip_t=$(strip_volatile t)
  strip_v=$(strip_volatile v)
  strip_g=$(strip_volatile g)

  # entities table: scoped by project='ktx'.
  $PSQL -At -c "
    SELECT 'entities', COUNT(*),
           COALESCE(MD5(string_agg(stripped::text, '|' ORDER BY stripped::text)), 'EMPTY')
    FROM (
      SELECT ${strip_t} AS stripped
      FROM ${ENTITIES_TABLE} t WHERE project='ktx'
    ) x
  " >> "$outfile"

  # *_versions tables: join entities on entity_id, filter project='ktx'.
  for t in "${VERSIONS_TABLES[@]}"; do
    $PSQL -At -c "
      SELECT '${t}', COUNT(*),
             COALESCE(MD5(string_agg(stripped::text, '|' ORDER BY stripped::text)), 'EMPTY')
      FROM (
        SELECT ${strip_v} AS stripped
        FROM ${t} v
        JOIN entities e ON v.entity_id = e.id
        WHERE e.project = 'ktx'
      ) x
    " >> "$outfile"
  done

  # gameplay_* tables: scoped by gameplay_source_id='ktx'.
  for t in "${GAMEPLAY_TABLES[@]}"; do
    $PSQL -At -c "
      SELECT '${t}', COUNT(*),
             COALESCE(MD5(string_agg(stripped::text, '|' ORDER BY stripped::text)), 'EMPTY')
      FROM (
        SELECT ${strip_g} AS stripped
        FROM ${t} g WHERE gameplay_source_id='ktx'
      ) x
    " >> "$outfile"
  done

  echo "$outfile"
}

echo "=== KTX idempotency probe ==="
echo
echo "[1/3] Pre-run snapshot..."
PRE=$(snapshot pre)

echo "[2/3] Re-run KTX dispatch (--force bypasses >50% drop guard) ..."
# extract-tag auto-resolves HEAD_ORDINAL when --version=head (see
# scripts/load-knowledge/index.ts), so --ordinal is unneeded here.
npm --prefix apps/qw-oracle --no-workspaces run load-knowledge -- extract-tag --project ktx --version head --force 2>&1 | tail -20

echo "[3/3] Post-run snapshot..."
POST=$(snapshot post)

echo
echo "Diff (pre vs post):"
DIFF_OUT=$(diff "$PRE" "$POST" || true)
if [ -z "$DIFF_OUT" ]; then
  echo "  (no drift; idempotent)"
  rm -f "$PRE" "$POST"
  exit 0
fi
echo "$DIFF_OUT"
echo
echo "FAIL: idempotency violated. Pre-run snapshot at $PRE, post-run at $POST."
exit 1
