import type { ConversionResult } from "../converter/converter.js";

/**
 * Shared config serialization logic.
 * Used by both writeFteConfig and writeEzQuakeConfig.
 *
 * Output format:
 *   // -- Settings --
 *   cvar "value"
 *
 *   // -- Binds --
 *   bind key "action"
 */
export function writeConfig(result: ConversionResult, clientName: string): string {
  const lines: string[] = [
    `// Generated by Slipgate QW Config Converter (${clientName})`,
    "",
  ];

  // Cvars — sorted alphabetically
  const sortedCvars = Array.from(result.targetCvars.entries()).sort(([a], [b]) =>
    a.localeCompare(b)
  );

  lines.push("// -- Settings --");
  for (const [name, value] of sortedCvars) {
    lines.push(`${name} "${value}"`);
  }

  lines.push("");

  // Binds — sorted alphabetically
  const sortedBinds = Array.from(result.targetBinds.entries()).sort(([a], [b]) =>
    a.localeCompare(b)
  );

  lines.push("// -- Binds --");
  for (const [key, action] of sortedBinds) {
    lines.push(`bind ${key} "${action}"`);
  }

  return lines.join("\n");
}
