// apps/qw-oracle/scripts/load-knowledge/idempotency.ts
//
// Universal idempotency probe. Snapshots Layer 1 rows for a project,
// re-runs extract-tag with --force, re-snapshots, and diffs counts +
// content hashes per table. Lift of the KTX-only idempotency-ktx.sh
// bash probe (deleted in the same phase commit) into the load-knowledge
// dispatcher.
//
// Per docs/superpowers/plans/2026-05-08-extractor-discipline-catchup/
// decisions.md:
//   D2 -- CI-readiness conventions (--project / --all / --json / --help,
//         env-var driven DATABASE_URL, exit 0 PASS / non-zero FAIL).
//   D3 -- Per-project config dict shipped inline; not a unified registry.
//   D4 -- Dispatcher case mirrors quality-grid pattern.
//   D6 -- Phase commit body captures cross-project audit findings.
//   D12 -- JSONB binding rule (probe is read-only against JSONB; no
//          stringification).
//
// Run:
//   bun run load-knowledge -- idempotency --project <p>
//   bun run load-knowledge -- idempotency --all
//   bun run load-knowledge -- idempotency --project <p> --json
//   bun run load-knowledge -- idempotency --help

import { parseArgs } from 'util';
import type postgres from 'postgres';
import { sql } from './db.js';
import { extractTag } from './extract-tag.js';
import { HEAD_ORDINAL } from './constants.js';
import type { Project } from './types.js';

// Project type carries 'qw' (game-content namespace; no engine source)
// alongside the extracted projects. The idempotency gate scopes to the
// 5 actively-extracted projects only; qtv/qwfwd are frozen vendored
// snapshots that bypass extract-tag entirely (D1).
type IdempotencyProject = Exclude<Project, 'qw' | 'qtv' | 'qwfwd'>;

const PROJECTS: readonly IdempotencyProject[] = [
  'ezquake',
  'fte',
  'qwcl',
  'mvdsv',
  'ktx',
] as const;

interface ProjectIdempotencyConfig {
  // *_versions tables that hold this project's per-version rows. Joined
  // to entities via entity_id and filtered by project=<p>. Determined
  // empirically from the dev DB's row-presence matrix at scaffold time
  // (2026-05-08): each table listed here has non-zero rows for the
  // owning project. Tables with zero rows for the project are omitted.
  versionsTables: readonly string[];
  // KTX writes id1-style game-mechanics rows scoped by
  // gameplay_source_id='<project>'. Other extracted projects: empty array.
  // (id1 is a separate seed namespace, not extracted via extract-tag.)
  gameplayTables: readonly string[];
}

const PROJECT_IDEMPOTENCY_CONFIG: Record<IdempotencyProject, ProjectIdempotencyConfig> = {
  ezquake: {
    versionsTables: [
      'asset_category_versions',
      'cmdline_param_versions',
      'command_versions',
      'cvar_versions',
      'flag_bit_versions',
      'hud_element_versions',
      'keyname_versions',
      'macro_versions',
      'ruleset_versions',
      'token_primitive_versions',
    ],
    gameplayTables: [],
  },
  fte: {
    versionsTables: [
      'asset_category_versions',
      'cmdline_param_versions',
      'command_versions',
      'cvar_alias_versions',
      'cvar_versions',
      'macro_versions',
    ],
    gameplayTables: [],
  },
  qwcl: {
    versionsTables: [
      'cmdline_param_versions',
      'command_versions',
      'cvar_versions',
    ],
    gameplayTables: [],
  },
  mvdsv: {
    versionsTables: [
      'cmdline_param_versions',
      'command_versions',
      'cvar_versions',
      'info_key_versions',
      'log_template_versions',
      'protocol_message_versions',
      'qc_builtin_versions',
    ],
    gameplayTables: [],
  },
  ktx: {
    versionsTables: [
      'command_versions',
      'cvar_versions',
      'info_key_versions',
      'log_template_versions',
      'match_event_versions',
    ],
    gameplayTables: [
      'gameplay_entity_defs',
      'gameplay_mechanics',
    ],
  },
};

// Volatile-column strip list. Stripped via `to_jsonb(row) - 'key'` chain;
// the `-` operator is a no-op when the key is absent on the table, so a
// single list covers all three buckets (entities / *_versions / gameplay_*).
//
// Stripped (volatile -- expected to drift across re-runs of an idempotent
// loader; would mask the actual data-equivalence question):
//   updated_at                    -- bumped on every entities UPSERT.
//   extracted_at                  -- bumped on every *_versions UPSERT.
//   description_embedding         -- regenerated by the embed pipeline.
//   description_embedding_sha256  -- derived from description text.
//   description_embedding_stale   -- transient; flips during embed pipeline.
//
// NOT stripped (deterministic from inputs -- drift is a real signal):
//   entities.created_at           -- set once on insert; drift means a row
//                                    was deleted + reinserted, which IS
//                                    what this probe must catch.
//   entities.description          -- derived deterministically from
//                                    source/help-JSON.
//   entities.description_origin   -- migration 012; deterministic CASE on
//                                    source/help-JSON state.
//   entities.description_tsv      -- generated column; deterministic from
//                                    description.
//   *_versions body fields        -- the whole point of the probe.
//   gameplay_* JSONB              -- ruleset_gate_json, props_json are
//                                    parsed deterministically from
//                                    extracted JSON.
function stripFragment(s: postgres.Sql, alias: 't' | 'v' | 'g') {
  // Three explicit fragments instead of dynamic alias substitution -- the
  // alias set is fixed (3 buckets), and explicit fragments keep the SQL
  // human-readable + sql-template-safe (no `unsafe()`, no
  // identifier-as-alias quoting hazards).
  if (alias === 't') {
    return s`(to_jsonb(t) - 'updated_at' - 'extracted_at' - 'description_embedding' - 'description_embedding_sha256' - 'description_embedding_stale')`;
  }
  if (alias === 'v') {
    return s`(to_jsonb(v) - 'updated_at' - 'extracted_at' - 'description_embedding' - 'description_embedding_sha256' - 'description_embedding_stale')`;
  }
  return s`(to_jsonb(g) - 'updated_at' - 'extracted_at' - 'description_embedding' - 'description_embedding_sha256' - 'description_embedding_stale')`;
}

interface TableSnapshot {
  table: string;
  count: number;
  hash: string;
}

interface TableDrift {
  table: string;
  preCount: number;
  postCount: number;
  preHash: string;
  postHash: string;
}

interface IdempotencyResult {
  project: IdempotencyProject;
  status: 'PASS' | 'FAIL';
  tablesChecked: number;
  driftedCount: number;
  drifted: TableDrift[];
  summary: string;
}

async function snapshotProject(
  s: postgres.Sql,
  project: IdempotencyProject,
): Promise<Map<string, TableSnapshot>> {
  const config = PROJECT_IDEMPOTENCY_CONFIG[project];
  const tables = new Map<string, TableSnapshot>();

  // entities: scoped by project=<p>.
  const stripT = stripFragment(s, 't');
  const entitiesRows = await s<{ count: number; hash: string }[]>`
    SELECT COUNT(*)::int AS count,
           COALESCE(MD5(string_agg(stripped::text, '|' ORDER BY stripped::text)), 'EMPTY') AS hash
    FROM (
      SELECT ${stripT} AS stripped
      FROM entities t WHERE project = ${project}
    ) x
  `;
  tables.set('entities', {
    table: 'entities',
    count: entitiesRows[0]!.count,
    hash: entitiesRows[0]!.hash,
  });

  // *_versions: join entities on entity_id, filter project=<p>.
  const stripV = stripFragment(s, 'v');
  for (const t of config.versionsTables) {
    const rows = await s<{ count: number; hash: string }[]>`
      SELECT COUNT(*)::int AS count,
             COALESCE(MD5(string_agg(stripped::text, '|' ORDER BY stripped::text)), 'EMPTY') AS hash
      FROM (
        SELECT ${stripV} AS stripped
        FROM ${s(t)} v
        JOIN entities e ON v.entity_id = e.id
        WHERE e.project = ${project}
      ) x
    `;
    tables.set(t, { table: t, count: rows[0]!.count, hash: rows[0]!.hash });
  }

  // gameplay_*: scoped by gameplay_source_id=<p>. KTX-only today (other
  // projects ship empty gameplayTables in the config dict).
  const stripG = stripFragment(s, 'g');
  for (const t of config.gameplayTables) {
    const rows = await s<{ count: number; hash: string }[]>`
      SELECT COUNT(*)::int AS count,
             COALESCE(MD5(string_agg(stripped::text, '|' ORDER BY stripped::text)), 'EMPTY') AS hash
      FROM (
        SELECT ${stripG} AS stripped
        FROM ${s(t)} g WHERE gameplay_source_id = ${project}
      ) x
    `;
    tables.set(t, { table: t, count: rows[0]!.count, hash: rows[0]!.hash });
  }

  return tables;
}

function diffSnapshots(
  pre: Map<string, TableSnapshot>,
  post: Map<string, TableSnapshot>,
): TableDrift[] {
  const drifted: TableDrift[] = [];
  for (const [table, preSnap] of pre) {
    const postSnap = post.get(table);
    if (!postSnap) {
      drifted.push({
        table,
        preCount: preSnap.count,
        postCount: 0,
        preHash: preSnap.hash,
        postHash: 'MISSING',
      });
      continue;
    }
    if (preSnap.count !== postSnap.count || preSnap.hash !== postSnap.hash) {
      drifted.push({
        table,
        preCount: preSnap.count,
        postCount: postSnap.count,
        preHash: preSnap.hash,
        postHash: postSnap.hash,
      });
    }
  }
  return drifted;
}

export async function runIdempotency(opts: {
  sql: postgres.Sql;
  project: IdempotencyProject;
}): Promise<IdempotencyResult> {
  const { project } = opts;
  process.stderr.write(`[idempotency:${project}] pre snapshot...\n`);
  const pre = await snapshotProject(opts.sql, project);

  process.stderr.write(
    `[idempotency:${project}] re-running extract-tag --version head --force...\n`,
  );
  await extractTag({
    sql: opts.sql,
    project,
    version: 'head',
    ordinal: HEAD_ORDINAL,
    force: true,
  });

  process.stderr.write(`[idempotency:${project}] post snapshot...\n`);
  const post = await snapshotProject(opts.sql, project);

  const drifted = diffSnapshots(pre, post);
  const status: 'PASS' | 'FAIL' = drifted.length === 0 ? 'PASS' : 'FAIL';
  const summary = drifted.length === 0
    ? `no drift across ${pre.size} tables (idempotent)`
    : `${drifted.length} of ${pre.size} tables drifted`;

  return {
    project,
    status,
    tablesChecked: pre.size,
    driftedCount: drifted.length,
    drifted,
    summary,
  };
}

function formatJson(results: IdempotencyResult[]): string {
  return JSON.stringify(results, null, 2);
}

function formatText(results: IdempotencyResult[]): string {
  const lines: string[] = [];
  for (const r of results) {
    lines.push(`=== ${r.project}: ${r.status} ===`);
    lines.push(`  ${r.summary}`);
    for (const d of r.drifted) {
      lines.push(
        `    ${d.table}: count ${d.preCount} -> ${d.postCount}; ` +
        `hash ${d.preHash.slice(0, 8)} -> ${d.postHash.slice(0, 8)}`,
      );
    }
  }
  return lines.join('\n');
}

function printHelp(): void {
  process.stderr.write(`
load-knowledge -- idempotency [options]

Snapshot Layer 1 rows for a project, re-run extract-tag --version head
--force, snapshot again, diff. Universal idempotency probe.

Options:
  --project <p>   Run probe against project <p>. One of:
                    ezquake | fte | qwcl | mvdsv | ktx.
  --all           Run probe sequentially against all 5 projects.
  --json          Emit JSON-formatted results to stdout.
  --help          Print this help and exit.

Exit codes:
  0   all targeted projects idempotent (no count or content drift) OR
      --help requested (informational success).
  1   one or more projects drifted; review output for failed tables.
  2   invalid arguments.

Required env: DATABASE_URL (default postgresql://qworacle:dev@127.0.0.1:5432/qw_oracle).
`.trim() + '\n');
}

export async function runIdempotencyCli(args: string[]): Promise<void> {
  const { values } = parseArgs({
    args,
    options: {
      project: { type: 'string' },
      all: { type: 'boolean' },
      json: { type: 'boolean' },
      help: { type: 'boolean' },
    },
  });

  if (values.help) {
    printHelp();
    process.exit(0);
  }

  const targets: IdempotencyProject[] = [];
  if (values.all) {
    targets.push(...PROJECTS);
  } else if (values.project) {
    if (!PROJECTS.includes(values.project as IdempotencyProject)) {
      process.stderr.write(
        `--project must be one of ${PROJECTS.join(' | ')}; got ${values.project}\n`,
      );
      process.exit(2);
    }
    targets.push(values.project as IdempotencyProject);
  } else {
    process.stderr.write('Either --project <p> or --all is required.\n');
    printHelp();
    process.exit(2);
  }

  const results: IdempotencyResult[] = [];
  for (const project of targets) {
    const r = await runIdempotency({ sql, project });
    results.push(r);
  }

  if (values.json) {
    process.stdout.write(formatJson(results) + '\n');
  } else {
    process.stdout.write(formatText(results) + '\n');
  }

  const failed = results.some((r) => r.status === 'FAIL');
  process.exitCode = failed ? 1 : 0;
}
